
package pc2.view;

import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import pc2.entidades.Carro;
import pc2.persistencia.CarroDAO;
import pc2.persistencia.ClienteDAO;

public class ListaCarros extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    private static Carro get(int linha) {
        throw new UnsupportedOperationException("Not supported yet."); // To change body of generated methods, choose
                                                                       // Tools | Templates.
    }

    private List<Carro> listaCarros;

    /**
     * Creates new form ListaClientes
     */
    public ListaCarros() {
        initComponents();
        carregarCarro();
    }

    // ListaCarros(ListaClientes aThis) {
    // throw new UnsupportedOperationException("Not supported yet."); //To change
    // body of generated methods, choose Tools | Templates.
    // }

    public void carregarCarro() {
        this.carregarCarro(false);
    }

    public void carregarCarro(boolean pesquisa) {
        // Pega o modelo da tabela de clientes
        DefaultTableModel modelo = (DefaultTableModel) tabCarros.getModel();
        // Limpar as linhas da tabela antes de preenchê-la
        modelo.setRowCount(0);
        // Desabilitar botões
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        // Verifica se fez uma pesquisa
        if (pesquisa == false) {
            // Carregar a lista de clientes
            listaCarros = CarroDAO.listarTodos();
        }
        // Preenche a tabela de clientes
        for (Carro ca : listaCarros) {
            // Cria a linha da tabela
            Object[] linha = { ca.getMarca(), ca.getModelo(), ca.getAnoModelo(), ca.getAnoFabricacao(), ca.getPlaca(),
                    ClienteDAO.pesquisarCpf(ca.getCpfCliente()).getNome() };
            // adiciono a linha na tabela
            modelo.addRow(linha);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabCarros = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        btnPequisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabCarros.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

        }, new String[] { "marca", "Modelo", "Anomodelo", "Anofabricacao", "placa", "Nome cliente" }) {
            Class[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.Integer.class,
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class };
            boolean[] canEdit = new boolean[] { false, true, true, false, true, true };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tabCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabCarrosMouseClicked(evt);
            }
        });
        tabCarros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabCarrosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabCarros);

        btnNovo.setText("Novo Carro");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir Carro");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar Carro");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
        });

        btnPequisar.setText("Pesquisar");
        btnPequisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPequisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup().addComponent(btnNovo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPesquisa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPequisar).addGap(18, 18, 18).addComponent(btnAlterar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluir)))
                        .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNovo).addComponent(btnExcluir).addComponent(btnAlterar)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPequisar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jScrollPane1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(126, Short.MAX_VALUE)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNovoActionPerformed

        CadastroCarros tela = new CadastroCarros(this);
        tela.setTitle("Cadastrar novo Carro");
        tela.setVisible(true);

    }// GEN-LAST:event_btnNovoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExcluirActionPerformed
        // Pega o número da linha selecionada pelo usuário
        int linha = tabCarros.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um carro para excluir!");
        } else {
            // Pega o cliente que está na linha selecionada
            Carro carro = listaCarros.get(linha);

            int confirmacao = JOptionPane.showConfirmDialog(null,
                    "Deseja realmente excluir o Carro " + carro.getPlaca() + "?", "Confirmação",
                    JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);

            if (confirmacao == JOptionPane.YES_OPTION) {
                if (CarroDAO.excluir(carro)) {
                    JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso!");
                    carregarCarro();
                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir cliente!");
                }
            }

        }

    }// GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAlterarActionPerformed
        int linha = tabCarros.getSelectedRow();
        if (linha > -1) {
            Carro ca = listaCarros.get(linha);

            CadastroCarros tela = new CadastroCarros(this);
            tela.setTitle("Alterar dados do carro");
            tela.setCliente(ca);
            tela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um carro para alterar!");
        }
    }// GEN-LAST:event_btnAlterarActionPerformed

    private void tabCarrosMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tabCarrosMouseClicked
        // Verifica se há uma linha selecionada
        if (tabCarros.getSelectedRow() > -1) {
            // Habilita os botões
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
        }
    }// GEN-LAST:event_tabCarrosMouseClicked

    private void tabCarrosKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_tabCarrosKeyPressed
        // Verifica se pressionou a tecla F4 do teclado
        if (evt.getKeyCode() == 115) {
            int linha = tabCarros.getSelectedRow();
            if (linha > -1) {
                Carro carro = listaCarros.get(linha);
            }
        }

        if (evt.getKeyCode() == 113) {
            int linha = tabCarros.getSelectedRow();
            if (linha > -1) {
                Carro carro = ListaCarros.get(linha);
                JOptionPane.showMessageDialog(null, carro);
            }
        }
    }// GEN-LAST:event_tabCarrosKeyPressed

    private void btnPequisarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPequisarActionPerformed
        listaCarros = CarroDAO.pesquisar(txtPesquisa.getText());
        carregarCarro(true);
    }// GEN-LAST:event_btnPequisarActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtPesquisaKeyPressed
        // Verifica se pressionou a tecla ENTER
        if (evt.getKeyCode() == 10) {
            listaCarros = CarroDAO.pesquisar(txtPesquisa.getText());
            carregarCarro(true);
        }

        // Verifica se pressionou a tecla ESC
        if (evt.getKeyCode() == 27) {
            txtPesquisa.setText("");
            carregarCarro();
        }
    }// GEN-LAST:event_txtPesquisaKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPequisar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabCarros;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
